
## Author : Amirul bin Abdullah
INTEL_PATH = /hpcfs/development/intel
MPI_PATH = $(INTEL_PATH)/impi_latest
INTEL_COMPESERXE = $(INTEL_PATH)/composerxe
MPIIFORT = mpiifort
MPI=mpicc
CPP=icc
CPP_FLAGS=-std=c++11 -m64
